
package com.gateway.channel.utils.ysf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderQueryService", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OrderQueryService {


    /**
     * 
     * @param orderQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByMerBillNo")
    @WebResult(name = "getOrderByMerBillNoResult", partName = "getOrderByMerBillNoResult")
    public String getOrderByMerBillNo(
			@WebParam(name = "orderQuery", partName = "orderQuery")
			String orderQuery);

    /**
     * 
     * @param orderQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByBankNo")
    @WebResult(name = "getOrderByBankNoResult", partName = "getOrderByBankNoResult")
    public String getOrderByBankNo(
			@WebParam(name = "orderQuery", partName = "orderQuery")
			String orderQuery);

    /**
     * 
     * @param orderQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByTime")
    @WebResult(name = "getOrderByTimeResult", partName = "getOrderByTimeResult")
    public String getOrderByTime(
			@WebParam(name = "orderQuery", partName = "orderQuery")
			String orderQuery);

}
