
package com.gateway.channel.utils.ysf;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSOrderQuery", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", wsdlLocation = "https://newpay.ips.com.cn/psfp-entry/services/order?wsdl")
public class WSOrderQuery
    extends Service
{

    private final static URL WSORDERQUERY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.gateway.channel.utils.ysf.WSOrderQuery.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.gateway.channel.utils.ysf.WSOrderQuery.class.getResource(".");
            url = new URL(baseUrl, "https://newpay.ips.com.cn/psfp-entry/services/order?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://newpay.ips.com.cn/psfp-entry/services/order?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSORDERQUERY_WSDL_LOCATION = url;
    }

    public WSOrderQuery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrderQuery() {
        super(WSORDERQUERY_WSDL_LOCATION, new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuery"));
    }

    /**
     * 
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap() {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuerySoap"), OrderQueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuerySoap"), OrderQueryService.class, features);
    }

}
